Update api-tests.yaml

diff --git a/.github/workflows/api-tests.yaml b/.github/workflows/api-tests.yaml
--- a/.github/workflows/api-tests.yaml
+++ b/.github/workflows/api-tests.yaml
@@ -6,6 +6,9 @@ jobs:
   automated-api-tests:
     runs-on: ubuntu-latest
 
+    env:
+      DATABASE_URI: ${{ secrets.DATABASE_URI }}
+
     steps:
       - uses: actions/checkout@v3
 
@@ -19,7 +22,13 @@ jobs:
         run: npm ci
 
       - name: Start the server
-        run: npm start & npx wait-on http://localhost:3000
+        run: |
+          npm start & npx wait-on http://localhost:3000 &
+          sleep 5
+          if grep -q "MongooseError: The \`uri\` parameter to \`openUri()\` must be a string, got \"undefined\"" server.log; then
+            echo "MongoDB connection failed. Stopping the workflow."
+            exit 1
+          fi
 
       - name: Install Postman CLI
         run: |
